name: RoK Data Sync
on:
  schedule:
    - cron: '*/30 * * * *' # Every 30 mins
  workflow_dispatch: # Allows manual run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: node sync.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
