name: RoK Data Sync
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Updated to v4
      - name: Install Node
        uses: actions/setup-node@v4 # Updated to v4
        with:
          node-version: '24' # Using the new default
      - run: npm install
      - run: node sync.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
